### ISSUE TITLE
pdf-info-query: epdfinfo: Unable to create temporary file

### ISSUE THREAD

**Issue by ShuguangSun** [vedang/pdf-tools#101] opened 2022-04-27 05:59 UTC
I updated pdf-tools today from melpa, and get an error:
`pdf-info-query: epdfinfo: Unable to create temporary file`

pdf-tools version: pdf-tools-20220426.2203

Emacs and System Information:
In GNU Emacs 29.0.50 (build 1, x86_64-w64-mingw32)
 of 2022-04-13 built on user
Repository revision: e587fc05a70c08a50258b152bb5403afd013007d
Repository branch: master
Windowing system distributor 'Microsoft Corp.', version 10.0.19044
System Description: Microsoft Windows 10 Pro (v10.0.2009.19044.1645)

Configured using:
 'configure --without-pop --with-native-image-api
 --with-native-compilation --without-compress-install

**Comment by vedang** [comment] 2022-05-01 14:47
In https://github.com/vedang/pdf-tools/commit/d63a1e7d87f9b0a19209f2eeb170bcf64612aa2f , I replaced the outdated `tempnam` with the suggested `mkstemp` to remove compilation warnings. It might be the reason why this happened, but I am not sure. Can you try the following two things? 

1. Remove and reinstall `pdf-tools` dependencies and `pdf-tools` itself. Make sure you remove all compiled artifacts when deleting the current install. This is to make sure the latest changes aren't working.
2. If the latest changes don't work, checkout `pdf-tools` at https://github.com/vedang/pdf-tools/commit/007fcf1fe9f8d74bcf7a88581b724b0f15022243 (the commit before the change) and see if it's working for you (to confirm that the bug is introduced by the change)

**Comment by ShuguangSun** [comment] 2022-05-05 07:27
I tried the two things. It works for at https://github.com/vedang/pdf-tools/commit/007fcf1fe9f8d74bcf7a88581b724b0f15022243, but it doesn't work for the current master.

**Comment by vedang** [comment] 2022-05-05 16:29
Great, thanks for testing this, I'll try and fix this over the weekend (or
I'll revert the commit until it can be properly fixed, thereby fixing the
master branch)

**Comment by sbstratos79** [comment] 2022-05-06 16:22
I can confirm that completely removing pdf-tools, reinstalling and building with 007fcf1fe9f8d74bcf7a88581b724b0f15022243 fixes the "Unable to create temporary file" issue. The pdfs are still completely broken for me however.

**Comment by vedang** [comment] 2022-05-10 01:04
Thank for you the confirmation @ShuguangSun and @sbstratos79 . I am reverting the commit right now and will open a separate issue to figure out how to correctly use `mkstemp` on Windows. I will close this ticket once the commit is reverted

**Closed** 2022-05-10 01:15 UTC
Labels: question, MSWindows
