### ISSUE TITLE
(pdf-tools-install) fails on macOS Sonoma 14.2.1 with poppler installed using homebrew

### ISSUE THREAD

**Issue by mikaelspringer** [vedang/pdf-tools#269] opened 2024-04-05 08:27 UTC
**Describe the bug**
After package update in Emacs, (pdf-tools-install) fails with error message "No package 'glib-2.0' found". Poppler 24.04.0 is installed using homebrew. glib 2.80.0 is installed using homebrew (as a dependency). 

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. Update Emacs packages.
2. Restart Emacs.
4. Answer "y" on the question: "Need to (re)build the epdfinfo program, do it now ? (y or n)".
5. Error: "error in process sentinel: Building the PDF Tools server failed"

**What is the expected behaviour?**
The rebuild of epdfinfo should execute without errors.

**Desktop**
Please complete the following information:

- OS: macOS Sonoma 14.2.1.
- Emacs Version: 30.0.50, emacs-plus@30, installed using homebrew.
- Poppler Version: 24.04.0, installed using homebrew.

**Your pdf-tools install**
Please complete the following information:

- `pdf-tools` Version: 20240317.848
- `pdf-tools` customization / configuration that you use
```

(use-package pdf-tools
  :ensure t
  :if (eq system-type 'darwin)
  :config
  (pdf-tools-install))

```

**Comment by vedang** [comment] 2024-04-05 13:05
The problem is that something seems to have changed in the way `brew` installs `glib`, due to which `pkg-config` does not find the glib headers. 

To fix this, I have updated the `autobuild` script to manually modify the `PKG_CONFIG_PATH`. This should fix the problem. 

I will test the change and close this issue via the commit once I push it. You will need to update your version of `pdf-tools` and then restart Emacs to trigger the re-build again. (It might take a few hours for Melpa to pick up the latest version of the `pdf-tools`)

I will create a linked issue to investigate a better long-term solution to this problem.

**Closed** 2024-04-05 13:15 UTC

**Comment by mikaelspringer** [comment] 2024-04-06 12:39
I updated the Emacs pdf-tools package and restarted. When prompted to rebuild epdfinfo I answered 'y', the compilation succeeded and now everything is working again. Thanks!

**Comment by Binjian** [comment] 2024-04-20 12:28
The build seem to have failed again on my mbp m3/Sonoma 14.4.1/Emacs 30.0.5. I double checked, the commit was there, pinned by doom emacs. 
Somehow I came across this issue on homebrew. I'm not sure if it's relevant.

https://github.com/Homebrew/homebrew-core/issues/67950

**Comment by gusgustavsohn** [comment] 2024-04-25 00:56
@mikaelspringer I'm facing a rather similar issue but reinstalling doesn't seem to do the trick, unlike what happened in your case. I'm curious: when you say that your reinstallation succeeded, did it show any warnings? My installs do succeed but I receive 2 warnings and I'm trying to determine if that could be the cause of pdf-tools not working for me. Thanks in advance for all your help.

**Comment by scbagby** [comment] 2024-04-30 03:34
In MacOS 14.4.1, with pdf-tools (20240429.407) installed and loaded via 

`(use-package pdf-tools
  :ensure t
  :init
  (pdf-tools-install))`

I'm also seeing two warnings

1.
`epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is provided
      for compatibility reasons only. Due to security concerns inherent in the
      design of tempnam(3), it is highly recommended that you use mkstemp(3)
      instead. [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");`

2. `epdfinfo.c:1576:5: warning: 'poppler_page_get_selection_region' is deprecated:
      Use poppler_page_get_selected_region instead [-Wdeprecated-declarations]
    poppler_page_get_selection_region (page, 1.0, selection_style, region);
    ^`

when epdfinfo re-builds on launching Emacs and then a crash ("The epdfinfo server quit, restart it ?").  I've had no luck with uninstalling and reinstalling pdf-tools via MELPA.

**Comment by Ethanlinyf** [comment] 2024-08-11 08:09
Still has the error, see below for your reference @vedang 

./configure -q --bindir=/Users/ethanlin/.emacs.d/elpa/pdf-tools-20240429.407/ && make clean && make -s
configure: error: Package requirements (glib-2.0) were not met:

Package 'libpcre2-8', required by 'glib-2.0', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables glib_CFLAGS
and glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

-===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Sun Aug 11 18:04:42

**Comment by permezel** [comment] 2024-11-19 13:08
Also fails for me.  Tried all sorts of work-arounds as discussed here and in others.  Nothing works around the issue.

**Comment by MiragianCycle** [comment] 2024-11-22 05:20
Same here.

**Comment by permezel** [comment] 2026-01-03 23:06
`pcre2` was already uptodate, but I reinstalled, and rebuilt, and it works again for me.  Thanks!
