### ISSUE TITLE
revert-buffer not working on remote Tramp buffers

### ISSUE THREAD

**Issue by iostapyshyn** [vedang/pdf-tools#126] opened 2022-07-10 13:08 UTC
A pdf opened over Tramp is not getting updated on `revert-buffer`. Instead, a local outdated copy is being reloaded.

Relevant thread on `tramp-devel`: https://mail.gnu.org/archive/html/tramp-devel/2017-04/msg00000.html

**Comment by vedang** [comment] 2022-07-10 15:16
Hi @iostapyshyn , 

This is not a `pdf-tools` problem. `revert-buffer` works correctly on PDF files opened via `pdf-tools`, it looks like a problem specific to `doc-view`. 

Closing this issue.

**Comment by iostapyshyn** [comment] 2022-07-10 16:53
@vedang I can reproduce this with current `pdf-tools` master branch. Obviously this is a `pdf-tools` issue, I didn't mention `doc-view` in my issue at all.

**Comment by vedang** [comment] 2022-07-13 20:50
@iostapyshyn : The thread you linked has the following title: `docview & tramp revert-buffer problem`. I read the title and assumed that you were trying to be helpful by pointing me to a potential `pdf-tools` problem. Hence my reply. 

I have now read through the thread, which mentions clearly that it's a docview problem. I have also personally tried opening a remote PDF file through Tramp on my setup. It works fine for `pdf-tools` (i.e. I cannot reproduce the problem you are mentioning). 

I will re-open this ticket and leave it open until I can try again with a `emacs -q` session to check if there is any problem with `pdf-tools` and `tramp`.

**Comment by iostapyshyn** [comment] 2022-07-14 21:23
Also reported previously in `politza` repo: https://github.com/politza/pdf-tools/issues/163

**Closed** 2022-07-21 01:05 UTC
